"""initial schema

Revision ID: 1b84f071c74f
Revises: 
Create Date: 2025-09-11 16:43:36.488762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b84f071c74f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fbref_results',
    sa.Column('game', sa.Text(), nullable=False),
    sa.Column('game_id', sa.Text(), nullable=True),
    sa.Column('league', sa.Text(), nullable=True),
    sa.Column('season', sa.Text(), nullable=True),
    sa.Column('round', sa.Text(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('day', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('home_team', sa.Text(), nullable=True),
    sa.Column('home_xg', sa.Float(), nullable=True),
    sa.Column('score', sa.Text(), nullable=True),
    sa.Column('away_xg', sa.Float(), nullable=True),
    sa.Column('away_team', sa.Text(), nullable=True),
    sa.Column('attendance', sa.Integer(), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('referee', sa.Text(), nullable=True),
    sa.Column('match_report', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('away_g', sa.Integer(), nullable=True),
    sa.Column('home_g', sa.Integer(), nullable=True),
    sa.Column('away_sat', sa.Integer(), nullable=True),
    sa.Column('home_sat', sa.Integer(), nullable=True),
    sa.Column('datetime_insert', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('game', name='fbref_results_pkey')
    )
    op.create_index('ix_fbref_away_date', 'fbref_results', ['away_team', 'date'], unique=False)
    op.create_index('ix_fbref_date_not_null', 'fbref_results', ['date'], unique=False, postgresql_where=sa.text('date IS NOT NULL'))
    op.create_index('ix_fbref_home_date', 'fbref_results', ['home_team', 'date'], unique=False)
    op.create_table('models_results',
    sa.Column('datetime_inference', sa.TIMESTAMP(), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('game_id', sa.String(length=255), nullable=True),
    sa.Column('game', sa.String(length=255), nullable=False),
    sa.Column('date_match', sa.Date(), nullable=False),
    sa.Column('time_match', sa.Time(), nullable=True),
    sa.Column('home_team', sa.String(length=255), nullable=False),
    sa.Column('away_team', sa.String(length=255), nullable=False),
    sa.Column('prob_home_win', sa.Float(), nullable=True),
    sa.Column('prob_draw', sa.Float(), nullable=True),
    sa.Column('prob_away_win', sa.Float(), nullable=True),
    sa.Column('prob_home_team_score', sa.Float(), nullable=True),
    sa.Column('prob_away_team_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('datetime_inference', 'model', 'game', name='models_results_datetime_inference_model_game_key')
    )
    op.create_table('optim_results',
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('sport_key', sa.String(length=50), nullable=True),
    sa.Column('game', sa.String(length=100), nullable=True),
    sa.Column('date_match', sa.Date(), nullable=True),
    sa.Column('time_match', sa.Time(), nullable=True),
    sa.Column('home_team', sa.String(length=100), nullable=True),
    sa.Column('away_team', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('datetime_inference', sa.TIMESTAMP(), nullable=False),
    sa.Column('prob_home_win', sa.Float(), nullable=True),
    sa.Column('prob_draw', sa.Float(), nullable=True),
    sa.Column('prob_away_win', sa.Float(), nullable=True),
    sa.Column('odds_home', sa.Float(), nullable=True),
    sa.Column('odds_draw', sa.Float(), nullable=True),
    sa.Column('odds_away', sa.Float(), nullable=True),
    sa.Column('bookmaker_home', sa.String(length=100), nullable=True),
    sa.Column('bookmaker_draw', sa.String(length=100), nullable=True),
    sa.Column('bookmaker_away', sa.String(length=100), nullable=True),
    sa.Column('f_home', sa.Float(), nullable=True),
    sa.Column('f_draw', sa.Float(), nullable=True),
    sa.Column('f_away', sa.Float(), nullable=True),
    sa.Column('datetime_optim', sa.TIMESTAMP(), nullable=False),
    sa.Column('utility_fn', sa.String(length=255), server_default=sa.text("'Kelly'"), nullable=False),
    sa.Column('odds_home_datetime', sa.TIMESTAMP(), nullable=True),
    sa.Column('odds_draw_datetime', sa.TIMESTAMP(), nullable=True),
    sa.Column('odds_away_datetime', sa.TIMESTAMP(), nullable=True),
    sa.Column('optim_label', sa.String(length=255), server_default=sa.text("'manual'"), nullable=True),
    sa.PrimaryKeyConstraint('match_id', 'model', 'datetime_inference', 'utility_fn', 'datetime_optim', name='optim_results_pkey')
    )
    op.create_table('soccer_odds',
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('sport_key', sa.String(length=100), nullable=True),
    sa.Column('sport_title', sa.String(length=100), nullable=True),
    sa.Column('commence_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('home_team', sa.String(length=100), nullable=True),
    sa.Column('away_team', sa.String(length=100), nullable=True),
    sa.Column('bookmaker_key', sa.String(length=50), nullable=False),
    sa.Column('bookmaker_title', sa.String(length=100), nullable=True),
    sa.Column('bookmaker_last_update', sa.TIMESTAMP(), nullable=True),
    sa.Column('market_key', sa.String(length=50), nullable=False),
    sa.Column('market_last_update', sa.TIMESTAMP(), nullable=False),
    sa.Column('outcome_name', sa.String(length=100), nullable=False),
    sa.Column('outcome_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('datetime_insert', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('match_id', 'bookmaker_key', 'market_key', 'outcome_name', 'market_last_update', name='soccer_odds_pkey')
    )
    op.create_table('sofifa_teams_stats',
    sa.Column('league', sa.String(length=255), nullable=True),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('overall', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('midfield', sa.Integer(), nullable=True),
    sa.Column('defence', sa.Integer(), nullable=True),
    sa.Column('transfer_budget', sa.Integer(), nullable=True),
    sa.Column('club_worth', sa.Float(), nullable=True),
    sa.Column('build_up_speed', sa.String(length=255), nullable=True),
    sa.Column('build_up_dribbling', sa.String(length=255), nullable=True),
    sa.Column('build_up_passing', sa.String(length=255), nullable=True),
    sa.Column('build_up_positioning', sa.String(length=255), nullable=True),
    sa.Column('chance_creation_crossing', sa.String(length=255), nullable=True),
    sa.Column('chance_creation_passing', sa.String(length=255), nullable=True),
    sa.Column('chance_creation_shooting', sa.String(length=255), nullable=True),
    sa.Column('chance_creation_positioning', sa.String(length=255), nullable=True),
    sa.Column('defence_aggression', sa.String(length=255), nullable=True),
    sa.Column('defence_pressure', sa.String(length=255), nullable=True),
    sa.Column('defence_team_width', sa.String(length=255), nullable=True),
    sa.Column('defence_defender_line', sa.String(length=255), nullable=True),
    sa.Column('defence_domestic_prestige', sa.Integer(), nullable=True),
    sa.Column('international_prestige', sa.Integer(), nullable=True),
    sa.Column('players', sa.Integer(), nullable=True),
    sa.Column('starting_xi_average_age', sa.Float(), nullable=True),
    sa.Column('whole_team_average_age', sa.Float(), nullable=True),
    sa.Column('fifa_edition', sa.String(length=255), nullable=True),
    sa.Column('update', sa.TIMESTAMP(), nullable=False),
    sa.Column('datetime_insert', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('team', 'update', name='unique_team_update')
    )
    op.create_index('ix_sofifa_team_update_desc', 'sofifa_teams_stats', ['team', sa.literal_column('update DESC')], unique=False, postgresql_include=('overall', 'attack', 'midfield', 'defence', 'transfer_budget', 'club_worth'))
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('team_id', name=op.f('teams_pkey')),
    sa.UniqueConstraint('canonical_name', name='uq_teams_canonical_name')
    )
    op.create_table('team_alias',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_name', sa.String(length=255), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], name='fk_team_alias_team_id_teams'),
    sa.PrimaryKeyConstraint('source', 'raw_name', name='team_alias_pkey')
    )
    op.create_index('ix_team_alias_team_id', 'team_alias', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_alias_team_id', table_name='team_alias')
    op.drop_table('team_alias')
    op.drop_table('teams')
    op.drop_index('ix_sofifa_team_update_desc', table_name='sofifa_teams_stats', postgresql_include=('overall', 'attack', 'midfield', 'defence', 'transfer_budget', 'club_worth'))
    op.drop_table('sofifa_teams_stats')
    op.drop_table('soccer_odds')
    op.drop_table('optim_results')
    op.drop_table('models_results')
    op.drop_index('ix_fbref_home_date', table_name='fbref_results')
    op.drop_index('ix_fbref_date_not_null', table_name='fbref_results', postgresql_where=sa.text('date IS NOT NULL'))
    op.drop_index('ix_fbref_away_date', table_name='fbref_results')
    op.drop_table('fbref_results')
    # ### end Alembic commands ###
