CREATE TABLE matches_fbref AS
SELECT * FROM (
    SELECT
        game_id::TEXT,
        league::TEXT,
        season::TEXT,
        game::TEXT,
        round::TEXT,
        week::INTEGER,
        day::TEXT,
        date::DATE,
        time::TIME WITHOUT TIME ZONE,
        home_team::TEXT,
        home_xg::DOUBLE PRECISION,
        score::TEXT,
        away_xg::DOUBLE PRECISION,
        away_team::TEXT,
        attendance::INTEGER,
        venue::TEXT,
        referee::TEXT,
        match_report::TEXT,
        notes::TEXT,
        index::INTEGER,
        away_g::INTEGER,
        home_g::INTEGER,
        away_sat::INTEGER,
        home_sat::INTEGER
    FROM matches_euro
    UNION ALL
    SELECT
        game_id::TEXT,
        league::TEXT,
        season::TEXT,
        game::TEXT,
        round::TEXT,
        week::INTEGER,
        day::TEXT,
        date::DATE,
        time::TIME WITHOUT TIME ZONE,
        home_team::TEXT,
        home_xg::DOUBLE PRECISION,
        score::TEXT,
        away_xg::DOUBLE PRECISION,
        away_team::TEXT,
        attendance::INTEGER,
        venue::TEXT,
        referee::TEXT,
        match_report::TEXT,
        notes::TEXT,
        index::INTEGER,
        away_g::INTEGER,
        home_g::INTEGER,
        away_sat::INTEGER,
        home_sat::INTEGER
    FROM matches_big5
    UNION ALL
    SELECT
        game_id::TEXT,
        league::TEXT,
        season::TEXT,
        game::TEXT,
        round::TEXT,
        week::INTEGER,
        day::TEXT,
        date::DATE,
        time::TIME WITHOUT TIME ZONE,
        home_team::TEXT,
        home_xg::DOUBLE PRECISION,
        score::TEXT,
        away_xg::DOUBLE PRECISION,
        away_team::TEXT,
        attendance::INTEGER,
        venue::TEXT,
        referee::TEXT,
        match_report::TEXT,
        notes::TEXT,
        index::INTEGER,
        away_g::INTEGER,
        home_g::INTEGER,
        away_sat::INTEGER,
        home_sat::INTEGER
    FROM matches_wc
) AS combined
ORDER BY date;
