name: optim-sportbet

services:
  data-ingestion:
    build:
      context: ./data-ingestion-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./data-ingestion-service/.env
    volumes:
      - ./data-ingestion-service:/data-ingestion-service
    networks:
      - optim-sportbet-network

  pipelines:
    build:
      context: ./pipelines-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./pipelines-service/.env
    volumes:
      - ./pipelines-service:/pipelines-service
    networks:
      - optim-sportbet-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/mlflow
    networks:
      - optim-sportbet-network
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri 'postgresql+psycopg2://Consultant:Graphene2024!@soccerodds-psql-db.postgres.database.azure.com:5432/postgres'

networks:
  optim-sportbet-network:
    driver: bridge
