name: optim-sportbet

x-osportbet-common:
  &osportbet-common
  env_file:
    - .env
    - compose.env
    - secrets.env
  networks:
    - optim-sportbet-network

services:
  data-ingestion:
    <<: *osportbet-common
    build:
      context: ./data-ingestion
      dockerfile: Dockerfile
    image: optim-sportbet-data-ingestion:latest
    ports:
      - "${DATA_INGESTION_PORT_BRIDGE:-8000}:${DATA_INGESTION_PORT:-80}"

  pipelines:
    <<: *osportbet-common
    build:
      context: ./pipelines
      dockerfile: Dockerfile
    image: optim-sportbet-pipelines:latest
    ports:
      - "${PIPELINES_PORT_BRIDGE:-8001}:${PIPELINES_PORT:-80}"

  # mlflow:
  #   <<: *osportbet-common
  #   build:
  #     context: ./mlflow
  #     dockerfile: Dockerfile
  #   image: optim-sportbet-mlflow:latest
  #   ports:
  #     - "${MLFLOW_PORT_BRIDGE:-8002}:${MLFLOW_PORT:-80}"

  app-backend:
    <<: *osportbet-common
    build:
       context: ./app-backend
       dockerfile: Dockerfile
    image: optim-sportbet-app-backend:latest
    ports:
      - "${APP_BACKEND_PORT_BRIDGE:-8003}:${APP_BACKEND_PORT:-80}"
    
  app-frontend:
    <<: *osportbet-common
    build:
       context: ./app-frontend
       dockerfile: Dockerfile
    image: optim-sportbet-app-frontend:latest
    ports:
      - "${APP_FRONTEND_PORT_BRIDGE:-8004}:${APP_FRONTEND_PORT:-80}"

networks:
  optim-sportbet-network:
    driver: bridge
