apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
      - name: app-backend
        image: optimsportbets.azurecr.io/optim-sportbet-app-backend:1.2
        ports:
        - containerPort: 8103
        envFrom:
        - configMapRef:
            name: global-config
        - secretRef:
            name: global-secrets
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app-backend-service
spec:
  type: ClusterIP
  ports:
  - port: 8103
    targetPort: 80
  selector:
    app: app-backend
