apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
      - name: app-frontend
        image: optimsportbets.azurecr.io/optim-sportbet-app-frontend:1.2
        ports:
        - containerPort: 8104
        envFrom:
        - configMapRef:
            name: global-config
        - secretRef:
            name: global-secrets
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app-frontend-service
spec:
  type: LoadBalancer
  ports:
  - port: 8104
    targetPort: 80
  selector:
    app: app-frontend
