apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
      - name: data-ingestion
        image: optimsportbets.azurecr.io/optim-sportbet-data-ingestion:1.2
        ports:
        - containerPort: 8100
        envFrom:
        - configMapRef:
            name: global-config
        - secretRef:
            name: global-secrets
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
spec:
  type: ClusterIP
  ports:
  - port: 8100
    targetPort: 80
  selector:
    app: data-ingestion
