apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: optimsportbets.azurecr.io/optim-sportbet-mlflow:1.3
        ports:
        - containerPort: 8102
        envFrom:
        - configMapRef:
            name: global-config
        - secretRef:
            name: global-secrets
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: ClusterIP
  ports:
  - port: 8102
    targetPort: 80
  selector:
    app: mlflow
