apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logos-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.services.cdn.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.services.cdn.storage.size }}
