apiVersion: batch/v1
kind: CronJob
metadata:
  name: ingest-fbref-cronjob
  namespace: optimsportbets
spec:
  schedule: "0 * * * *" # every hour at minute 0
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: ingest-fbref
            image: curlimages/curl:7.85.0
            command: ["/bin/sh", "-c"]
            args:
              - |
                echo "Ingesting data from FBref"

                curl -X POST "${DATA_INGESTION_PROTOCOL}://${DATA_INGESTION_HOST}:${DATA_INGESTION_PORT}/${DATA_INGESTION_ENDPOINT_FBREF}" \
                  -H "accept: application/json" -H "Content-Type: application/json" \
                  -d '{
                        "get_current_season_only": true,
                        "use_cache": false,
                        "cutoff_days": 7,
                        "run_in_background": false
                      }'

                echo "Ingested FBref data"
            envFrom:
              - configMapRef:
                  name: global-config
          restartPolicy: OnFailure
