apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64 encoded dockerconfigjson> # Utilisation du compte admin de l'ACR