apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
type: Opaque
data:
  DB_PASSWORD: <base64 encoded password for postgres db on Azure>
  THE_ODDS_API_KEY: <base64 encoded the-odds-api API key>
  